### ISSUE TITLE
Design a common pattern for accepting arguments

### ISSUE THREAD

**Issue by docelic** [boomerdigital/solidus_graphql_api#17]
We should decide on a standard method for graphql calls to accept arguments.

Primarily, this would deal with how to support generic arguments such as some sort of query limits, common arguments accepted by many calls, and arguments like `first:` and `after:` for pagination.

But at the same time we can come up with a generic "template" for anything graphql-related that wants to use arguments provided in/with the query.

**Comment by dhonig** [comment]
Absolutely agree here. One Idea I had a while back was to make this API compatible with the Shopify API whenever and wherever possible. :imp:   Like my plan?   I don't know how sensible it is.  But imagine the utility!
https://help.shopify.com/en/api/graphiql


If we approached these questions by looking at the Shopify API, we would ease migration and also decided on patterns that should work for 99% of our own community.

**Comment by docelic** [comment]
Amazing, I had a couple various attempts to replicate parts of Shopify in the past! :)

**Comment by docelic** [comment]
@dhonig I was thinking further about your suggestion and obviously came to an idea that it would be useful to have a tool which can grab the complete S schema and create Solidus graphql files at will, rather than us having to do it manually once, and then keep checking periodically & manually whether Solidus GraphQL API is still up to date or not.

For this, I've created a tool which grabs the complete S GraphQL schema (using the introspection query) in JSON format, parses it, and outputs the files into the `graphql/` directory of solidus_graphql_api. Currently, it generates 135 GraphQL type files with 732 lines of code, including proper recognition of types and connections. These files are intended to always be maintained by the script (i.e. contain no manually added code) so the script can be run at any time, and any additions or removals in the upstream API can be detected simply with `git diff`/`git status`.

These stub files can already be `require`d into an app and generate no error. The only thing left to do then is to populate the resolver files with actual code that will be running in response to the queries.

I just have a couple things to solve before submitting a PR:

1) Some smaller improvements in generator code
2) Handle circular dependencies when 2 types depend on one another (e.g. Checkout and Customer, Collection and Product, ProductVariant and Product, and Blog and Article)
3) Add ability to generate empty/stub resolver files once (if they don't exist), and to append snippets of needed resolvers code into existing files
4) Test some actual calls like `{ shop { name } }`

Let me know in case you have any comments / suggestions re. the above. Thanks!

**Comment by dhonig** [comment]
Sounds fantastic. I had the idea of writings generator at the active record level.

**Comment by docelic** [comment]
Reached a milestone here -- some smaller issues remaining, but S schema in JSON format can now be converted to Solidus GraphQL API schema and loaded, and running queries with Graphiql works!

```
{ shop { name }}
```

Results in:

```
{
  "data": {
    "shop": {
      "name": "Sample Store"
    }
  }
}
```

Continuing to work on it. Will submit a PR when ready.

**Comment by docelic** [comment]
I was thinking about a way to separate auto-generated code from future implementation of the GraphQL fields, to keep it viable long term to check for changes in upstream schema by just doing `git diff`/`git status`, without being bothered by local implementation code.

For that purpose, each queryable object gets generated as 2 files:

1) `graphql/schema/types/<name>.rb`, containing the autogenerated schema-related code. These files are by default overwritten on every run of the generator.
2) `graphql/types/<name>.rb`, containing a module with empty method stubs. This module is `include`d from item 1), and our implementation code for a type lives here. These files are only created once if they don't exist, and are not subsequently overwritten.

The autogenerated code looks like this (for example, for root query "blogs"):

```
# schema/types/query_root.rb

class Spree::GraphQL::Schema::Types::QueryRoot < Spree::GraphQL::Schema::Types::BaseObject
  graphql_name 'QueryRoot'
  include ::Spree::GraphQL::Types::QueryRoot

  ...
  field :blogs, ::Spree::GraphQL::Schema::Types::Blog, null: false do
    description %q{List of the shop's blogs.}
    argument :first, ::GraphQL::Types::Int, required: false
    argument :after, ::GraphQL::Types::String, required: false
    argument :last, ::GraphQL::Types::Int, required: false
    argument :before, ::GraphQL::Types::String, required: false
    argument :reverse, ::GraphQL::Types::Boolean, required: false
    argument :sort_key, ::Spree::GraphQL::Schema::Types::BlogSortKeys, required: false
    argument :query, ::GraphQL::Types::String, required: false
  end
  ...
```

And in the implementation file:

```
# types/query_root.rb

module Spree::GraphQL::Types::QueryRoot

  ...

  # List of the shop's blogs.
  # Returns: ::Spree::GraphQL::Schema::Types::Blog, null: false
  def blogs(first: nil, after: nil, last: nil, before: nil, reverse: false, sort_key: 'ID', query: nil)
    raise ::Spree::GraphQL::NotImplementedError.new
  end

  ...
```

To implement the field, one then does one of two things:

1) Removes the `NotImplementedError` and fills the method with actual implementation (where `object` and `context` helpers are automatically available, per graphql-ruby)
2) Removes the `blogs` method altogether, to let `blogs` be called directly on the underlying object

I am continuing to work on the finishing touches and will submit a PR in the next couple days.

**Comment by docelic** [comment]
Currently I am running a test where I am taking the original S JSON schema text and comparing it to Solidus JSON schema text. Both JSONs come from running the introspection query against the respective servers.

The schema contents match in 99 out of 170 types, so 71 left to check and see what the issue with them is.

**Comment by docelic** [comment]
The schema looks mostly identical at this point, when the original schema is compared to the autogenerated schema in solidus_graphql_api.

Of two problems remaining, one is that in graphql-ruby (at least in version 1.8) connection types are defined to allow null default, whereas in S schema they are explicitly not null. (Default Edge for any type is `[TypeName]`, whereas S' Edge is `[TypeName!]!`.)

I will most probably handle this by following instructions from http://graphql-ruby.org/relay/connections.html and creating a custom non-null edge type.

**Comment by docelic** [comment]
I believe the generated GraphQL schema files look pretty well at this point. While I am thinking some more about them and trying to find any aspects I might have missed, I will be working on three next PRs:

One related to actually starting to use this schema. It will:

1) Remove the few currently-existing queries/mutations in solidus_graphql_api
2) Do minimal directory structure changes
3) Add a new query root with just one sample type (e.g. type `Shop` so that we can query for shop name, description, default currency, products etc.)
4) Adjust tests accordingly

One related to JWT authentication -- if the author of that Solidus PR related to JWT does not convert his code to gem himself, I might help speed it up.

And one related to globally unique IDs. I will see how S does it and submit a summary.

**Comment by dhonig** [comment]
I know the author of the JWT plugin.  we should try to collaborate.  I will try to facillitate that tomorrow.

**Comment by docelic** [comment]
Closing this one as the PR related to it (the complete schema) has been submitted.
