### ISSUE TITLE
Globally unique IDs

### ISSUE THREAD

**Issue by docelic** [boomerdigital/solidus_graphql_api#18]
S uses globally unique IDs which are opaque and their internal structure/content should not be relied upon. The final ID value is base64-encoded and sent to client as such.

(All this is in line with GraphQL's recommendations for globally unique IDs.)

An example ID looks like `Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0Lzk4OTUzMDcxMzk=`, and base64-decoded its corresponding value is:

```
gid://shopify/Product/9895307139
```

S allows using this globally unique ID to e.g. retrieve particular objects directly from the query root by asking for "node" with a corresponding id:

Example query:

```
{
node(id:"Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0Lzk4OTUzMDcxMzk=") {
  id
  ... on Product {
    handle
  }
}
}
```

Result:

```
{
  "data": {
    "node": {
      "id": "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0Lzk4OTUzMDcxMzk=",
      "handle": "dknypure-tee-with-underlayer"
    }
  }
}
```

**Comment by docelic** [comment]
In the current implementation, Solidus GraphQL API generates global IDs using graphql-ruby's built-in encoder.

It generates unencrypted, base64-encoded IDs in the form of "<Class>-<ID>", such as "Spree::Store-1".

**Comment by dhonig** [comment]
Id guess S is using SHA-256 or similar.   We could do the same but would need to come up with some kind of good algorithm to global guarantee global uniqueness/correctness.

**Comment by docelic** [comment]
@dhonig you mean to say it uses a different algorithm in production than it is available on the help site? The help site in its GraphQL uses an unencrypted, base64-encoded string in the form of "gid://shopify/Product/9895307139".

Regarding creating true UUIDs, maybe we can use a similar approach, but put store's domain in place of the brand name. Something like "gid://example.com/Product/9895307139". Sounds good?

**Comment by dhonig** [comment]
that sounds reasonable to me.   Thought I dislike having Class::Name as part of the uri
can we eliminate that or strip  off top level modules at least , for example Spree:: ?

**Comment by docelic** [comment]
Sure, sounds good!

**Comment by docelic** [comment]
Actually, it's not so simple:

1) Using the store domain in IDs requires us to fetch Spree::Store on every encoding or decoding of an ID to get the store's `url` value
2) If store domain changes, UUIDs are invalidated (not sure if this is a huge problem or not)
3) If we remove any part of class name (like that "Spree::"), then there is no way to guess during decode what prefix needs to be added back. It is simple for basic Solidus models, but if a customer has custom models which don't begin with Spree::, they won't work

Given the above, I'd suggest we keep the functionality as-is -- this means 1) generating the IDs in the most basic form of "ClassName-ID", and 2) ignoring (at least for the moment) the fact that our UUIDs are not globally unique but only unique per-app.

Does that sound like a reasonable compromise or you got a better idea? Thanks!

**Comment by docelic** [comment]
Agreed on leaving as-is for now. Closing.
