### ISSUE TITLE
Short-term dev plan

### ISSUE THREAD

**Issue by docelic** [boomerdigital/solidus_graphql_api#7]
While we are warming up with the actual GraphQL features, I would like to do some structure-related commits as follows:

1) Remove unused stub files from the extension (there may be more, but at a minimum this means removing CSS/js assets, install generator, routes file, and locales file)

2) Fix namespaces so that everything related to GraphQL is under `Spree::GraphQL`. (The naming doesn't matter -- after the namespace is standardized, it is very simple to rename it to anything else we may want such as `Solidus::GraphQL` or `Solidus::Graphql`.)

3) Add `me` query which returns the currently logged in user, if any

4) Standardize on naming for GraphQL connections. I would name all non-connection queries just `<name>` and connections `<name>_connection`. For example, `taxons` and `taxons_connection`.
This would make sure that everything can be used without and with the Connections pattern, and the implementations could be added at any time while ensuring that there would be no naming clashes nor uncertainty which one is being invoked

5) Do a smaller replacement in the names of type classes so that they follow the ruby-graphql recommendations. (E.g. `Solidus::GraphQL::OrderType` would become `Solidus::GraphQL::Types::Order`.)

Please let me know if the plan is OK with you, and if you advise that some of the items from the list not be implemented.

Thanks!

**Comment by docelic** [comment]
Most of the items here have been resolved, closing this one. (The first next steps are fixing/streamlining tests, adding tests for pieces of current functionality that don't have it, thinking about authentication/authorization, and thinking about GraphQL connections & paging.)

**Comment by dhonig** [comment]
Sounds good.  I like the idea in item issue 3 above.  I would name the query 'whoami' just to be more descriptive.  Lets open seperate issues for authentication/authorization ( JWT?),  Connections and paging.
